/*
 Script generated by PostgreSQL Comparer (clear command)
 This is the expected output structure for the clear command test.
 The actual script header will differ (it includes runtime dump info).

 Objects are dropped in dependency-safe order:
   1. Views (materialized first, then regular)
   2. Foreign key constraints
   3. Tables
   4. Routines (functions, procedures)
   5. Sequences
   6. Types (enums, composites, domains)
   7. Extensions
   8. Schemas
*/

begin;

/* ---> Drop Views --------------- */

/* Drop materialized view: clear_shared.mv_audit_stats */
drop materialized view if exists clear_shared.mv_audit_stats cascade;

/* Drop materialized view: clear_app.mv_daily_orders */
drop materialized view if exists clear_app.mv_daily_orders cascade;

/* Drop view: clear_app.v_top_customers */
drop view if exists clear_app.v_top_customers cascade;

/* Drop view: clear_app.v_customer_summary */
drop view if exists clear_app.v_customer_summary cascade;

/* ---> Drop Tables --------------- */

/* Drop foreign key: clear_app.orders.orders_customer_id_fkey */
alter table clear_app.orders drop constraint orders_customer_id_fkey;

/* Drop foreign key: clear_app.orders.orders_category_id_fkey */
alter table clear_app.orders drop constraint orders_category_id_fkey;

/* Drop foreign key: clear_app.order_items.order_items_order_id_fkey */
alter table clear_app.order_items drop constraint order_items_order_id_fkey;

/* Drop foreign key: clear_app.employees.employees_manager_id_fkey */
alter table clear_app.employees drop constraint employees_manager_id_fkey;

/* Drop table: clear_app.customers */
drop table if exists clear_app.customers cascade;

/* Drop table: clear_app.categories */
drop table if exists clear_app.categories cascade;

/* Drop table: clear_app.orders */
drop table if exists clear_app.orders cascade;

/* Drop table: clear_app.order_items */
drop table if exists clear_app.order_items cascade;

/* Drop table: clear_shared.audit_log */
drop table if exists clear_shared.audit_log cascade;

/* Drop table: clear_app.employees */
drop table if exists clear_app.employees cascade;

/* ---> Drop Routines --------------- */

/* Drop function: clear_app.update_timestamp */
drop function if exists clear_app.update_timestamp ();

/* Drop function: clear_app.get_customer_order_total */
drop function if exists clear_app.get_customer_order_total (p_customer_id integer);

/* Drop function: clear_shared.format_audit_entry */
drop function if exists clear_shared.format_audit_entry (p_id integer);

/* Drop function: clear_app.active_customer_count */
drop function if exists clear_app.active_customer_count ();

/* Drop procedure: clear_app.cleanup_old_orders */
drop procedure if exists clear_app.cleanup_old_orders (p_days integer);

/* ---> Drop Sequences --------------- */

/* Drop sequence: clear_app.customer_id_seq */
drop sequence if exists clear_app.customer_id_seq cascade;

/* Drop sequence: clear_shared.audit_id_seq */
drop sequence if exists clear_shared.audit_id_seq cascade;

/* ---> Drop Types --------------- */

/* Drop type: clear_app.order_status */
drop type if exists clear_app.order_status cascade;

/* Drop type: clear_app.full_name */
drop type if exists clear_app.full_name cascade;

/* Drop type: clear_app.positive_int */
drop type if exists clear_app.positive_int cascade;

/* ---> Drop Extensions --------------- */

/* Drop extension: uuid-ossp */
drop extension if exists "uuid-ossp" cascade;

/* Drop extension: pg_trgm */
drop extension if exists pg_trgm cascade;

/* ---> Drop Schemas --------------- */

/* Drop schema: clear_app */
drop schema if exists clear_app cascade;

/* Drop schema: clear_shared */
drop schema if exists clear_shared cascade;

commit;
