use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

// This is an information about a PostgreSQL sequence.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Sequence {
    pub schema: String, // Schema where the sequence is defined
    pub name: String, // Name of the sequence
    pub owner: String, // Owner of the sequence
    pub data_type: String, // Data type of the sequence
    pub start_value: Option<i64>, // Start value of the sequence
    pub min_value: Option<i64>, // Minimum value of the sequence
    pub max_value: Option<i64>, // Maximum value of the sequence
    pub increment_by: Option<i64>, // Increment value of the sequence
    pub cycle: bool, // Whether the sequence cycles
    pub cache_size: Option<i64>, // Cache size of the sequence
    pub last_value: Option<i64>, // Last value generated by the sequence
}

impl Sequence {
    /// Hash
    pub fn hash(&self) -> String {
        let mut hasher = Sha256::new();

        hasher.update(self.schema.as_bytes());
        hasher.update(self.name.as_bytes());
        hasher.update(self.data_type.as_bytes());
        if let Some(start_value) = self.start_value {
            hasher.update(start_value.to_string().as_bytes());
        }
        if let Some(min_value) = self.min_value {
            hasher.update(min_value.to_string().as_bytes());
        }
        if let Some(max_value) = self.max_value {
            hasher.update(max_value.to_string().as_bytes());
        }
        if let Some(increment_by) = self.increment_by {
            hasher.update(increment_by.to_string().as_bytes());
        }
        hasher.update(self.cycle.to_string().as_bytes());
        if let Some(cache_size) = self.cache_size {
            hasher.update(cache_size.to_string().as_bytes());
        }

        format!("{:x}", hasher.finalize())
    }

    /// Returns a string representation of the sequence
    pub fn get_script(&self) -> String {
        let mut script = String::new();
        
        // CREATE SEQUENCE statement
        script.push_str(&format!("create sequence {}.{}", self.schema, self.name));
        
        // Add AS clause for data type if not default
        if !self.data_type.is_empty() && self.data_type != "bigint" {
            script.push_str(&format!(" as {}", self.data_type));
        }
        
        // Add START WITH clause
        if let Some(start_value) = self.start_value {
            script.push_str(&format!(" start with {}", start_value));
        }
        
        // Add INCREMENT BY clause
        if let Some(increment_by) = self.increment_by {
            if increment_by != 1 {
                script.push_str(&format!(" increment by {}", increment_by));
            }
        }
        
        // Add MINVALUE clause
        if let Some(min_value) = self.min_value {
            script.push_str(&format!(" minvalue {}", min_value));
        } else {
            script.push_str(" no minvalue");
        }
        
        // Add MAXVALUE clause
        if let Some(max_value) = self.max_value {
            script.push_str(&format!(" maxvalue {}", max_value));
        } else {
            script.push_str(" no maxvalue");
        }
        
        // Add CACHE clause
        if let Some(cache_size) = self.cache_size {
            if cache_size != 1 {
                script.push_str(&format!(" cache {}", cache_size));
            }
        }
        
        // Add CYCLE clause
        if self.cycle {
            script.push_str(" cycle");
        } else {
            script.push_str(" no cycle");
        }
        
        script.push_str(";\n");
                
        script
    }

    pub fn get_drop_script(&self) -> String {
        format!("drop sequence {}.{};\n", self.schema, self.name)
    }

    pub fn get_alter_script(&self) -> String {
        let mut script = String::new();
        script.push_str(&format!("alter sequence {}.{} ", self.schema, self.name));
        
        if let Some(start_value) = self.start_value {
            script.push_str(&format!("start with {} ", start_value));
        }
        if let Some(increment_by) = self.increment_by {
            script.push_str(&format!("increment by {} ", increment_by));
        }
        if let Some(min_value) = self.min_value {
            script.push_str(&format!("minvalue {} ", min_value));
        } else {
            script.push_str("no minvalue ");
        }
        if let Some(max_value) = self.max_value {
            script.push_str(&format!("maxvalue {} ", max_value));
        } else {
            script.push_str("no maxvalue ");
        }
        if let Some(cache_size) = self.cache_size {
            script.push_str(&format!("cache {} ", cache_size));
        }
        if self.cycle {
            script.push_str("cycle ");
        } else {
            script.push_str("no cycle ");
        }
        
        script.push_str(";\n");
        
        script
    }
}