use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::utils::string_extensions::StringExt;

// This is an information about a PostgreSQL sequence.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Sequence {
    pub schema: String,                  // Schema where the sequence is defined
    pub name: String,                    // Name of the sequence
    pub owner: String,                   // Owner of the sequence
    pub data_type: String,               // Data type of the sequence
    pub start_value: Option<i64>,        // Start value of the sequence
    pub min_value: Option<i64>,          // Minimum value of the sequence
    pub max_value: Option<i64>,          // Maximum value of the sequence
    pub increment_by: Option<i64>,       // Increment value of the sequence
    pub cycle: bool,                     // Whether the sequence cycles
    pub cache_size: Option<i64>,         // Cache size of the sequence
    pub last_value: Option<i64>,         // Last value generated by the sequence
    pub owned_by_schema: Option<String>, // Schema of the owning table/column
    pub owned_by_table: Option<String>,  // Owning table name
    pub owned_by_column: Option<String>, // Owning column name
    pub is_identity: bool,               // Whether the sequence is an identity sequence
    #[serde(default)]
    pub is_unlogged: bool, // Whether the sequence is unlogged (relpersistence = 'u')
    #[serde(default)]
    pub comment: Option<String>, // Optional sequence comment
    pub hash: Option<String>,            // Hash of the sequence
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub acl: Vec<String>, // ACL (grant) entries for this sequence
}

impl Sequence {
    /// Creates a new Sequence with the given parameters
    #[allow(clippy::too_many_arguments)] // Sequence metadata naturally includes these fields from pg_sequence and pg_class.
    pub fn new(
        schema: String,
        name: String,
        owner: String,
        data_type: String,
        start_value: Option<i64>,
        min_value: Option<i64>,
        max_value: Option<i64>,
        increment_by: Option<i64>,
        cycle: bool,
        cache_size: Option<i64>,
        last_value: Option<i64>,
        owned_by_schema: Option<String>,
        owned_by_table: Option<String>,
        owned_by_column: Option<String>,
    ) -> Self {
        let mut sequence = Self {
            schema,
            name,
            owner,
            data_type,
            start_value,
            min_value,
            max_value,
            increment_by,
            cycle,
            cache_size,
            last_value,
            owned_by_schema,
            owned_by_table,
            owned_by_column,
            is_identity: false,
            is_unlogged: false,
            comment: None,
            hash: None,
            acl: Vec::new(),
        };
        sequence.hash();
        sequence
    }

    pub fn set_is_identity(&mut self, is_identity: bool) {
        self.is_identity = is_identity;
        self.hash();
    }

    /// Hash
    pub fn hash(&mut self) {
        let mut hasher = Sha256::new();

        hasher.update(self.schema.as_bytes());
        hasher.update(self.name.as_bytes());
        hasher.update(self.owner.as_bytes());
        hasher.update(self.data_type.as_bytes());
        if let Some(start_value) = self.start_value {
            hasher.update(start_value.to_string().as_bytes());
        }
        if let Some(min_value) = self.min_value {
            hasher.update(min_value.to_string().as_bytes());
        }
        if let Some(max_value) = self.max_value {
            hasher.update(max_value.to_string().as_bytes());
        }
        if let Some(increment_by) = self.increment_by {
            hasher.update(increment_by.to_string().as_bytes());
        }
        hasher.update(self.cycle.to_string().as_bytes());
        if let Some(cache_size) = self.cache_size {
            hasher.update(cache_size.to_string().as_bytes());
        }
        hasher.update(self.is_identity.to_string().as_bytes());
        hasher.update(self.is_unlogged.to_string().as_bytes());
        if let Some(comment) = &self.comment {
            hasher.update(comment.as_bytes());
        }

        self.hash = Some(format!("{:x}", hasher.finalize()));
    }

    fn render_owned_by_clause(&self) -> Option<String> {
        if self.is_identity {
            return None;
        }
        match (
            self.owned_by_schema.as_deref(),
            self.owned_by_table.as_deref(),
            self.owned_by_column.as_deref(),
        ) {
            (Some(schema), Some(table), Some(column)) => {
                Some(format!("owned by {}.{}.{}", schema, table, column))
            }
            _ => None,
        }
    }

    /// Returns a string representation of the sequence
    pub fn get_script(&self) -> String {
        let mut script = String::new();

        // CREATE SEQUENCE statement
        if self.is_unlogged {
            script.push_str(&format!(
                "create unlogged sequence {}.{}",
                self.schema, self.name
            ));
        } else {
            script.push_str(&format!("create sequence {}.{}", self.schema, self.name));
        }

        // Add AS clause for data type if not default
        if !self.data_type.is_empty() && self.data_type != "bigint" {
            script.push_str(&format!(" as {}", self.data_type));
        }

        // Add START WITH clause
        if let Some(start_value) = self.start_value {
            script.push_str(&format!(" start with {start_value}"));
        }

        // Add INCREMENT BY clause
        if let Some(increment_by) = self.increment_by
            && increment_by != 1
        {
            script.push_str(&format!(" increment by {increment_by}"));
        }

        // Add MINVALUE clause
        if let Some(min_value) = self.min_value {
            script.push_str(&format!(" minvalue {min_value}"));
        } else {
            script.push_str(" no minvalue");
        }

        // Add MAXVALUE clause
        if let Some(max_value) = self.max_value {
            script.push_str(&format!(" maxvalue {max_value}"));
        } else {
            script.push_str(" no maxvalue");
        }

        // Add CACHE clause
        if let Some(cache_size) = self.cache_size
            && cache_size != 1
        {
            script.push_str(&format!(" cache {cache_size}"));
        }

        // Add CYCLE clause
        if self.cycle {
            script.push_str(" cycle");
        } else {
            script.push_str(" no cycle");
        }

        script.append_block(";");

        script.push_str(&self.get_owner_script());

        if let Some(comment) = &self.comment {
            script.append_block(&format!(
                "comment on sequence {}.{} is '{}';",
                self.schema,
                self.name,
                comment.replace('\'', "''")
            ));
        }

        script
    }

    pub fn get_drop_script(&self) -> String {
        format!("drop sequence if exists {}.{};", self.schema, self.name).with_empty_lines()
    }

    /// Generates an ALTER SEQUENCE script targeting `self` (the desired state).
    ///
    /// `from` is the prior sequence state (always required — callers that own the comparer
    /// always have it).  `RESTART WITH` is emitted only when the sequence's effective current
    /// position would fall below the new `MINVALUE`, i.e. when
    /// `effective_current < new_minvalue` where
    /// `effective_current = from.last_value ?? from.start_value`.
    ///
    /// This is the minimal condition required to prevent PostgreSQL from rejecting the
    /// statement with:
    ///
    ///   ERROR: RESTART value (1) cannot be less than MINVALUE (10000000)
    ///
    /// Emitting `RESTART WITH` unconditionally (e.g. whenever `start_value` differs)
    /// would rewind a live sequence whose current position is already above the new
    /// `start_value`, risking duplicate-key violations.
    pub fn get_alter_script(&self, from: &Sequence) -> String {
        let mut clauses = Vec::new();

        // Handle logged/unlogged change
        let mut logging_script = String::new();
        if self.is_unlogged != from.is_unlogged {
            if self.is_unlogged {
                logging_script =
                    format!("alter sequence {}.{} set unlogged;", self.schema, self.name)
                        .with_empty_lines();
            } else {
                logging_script =
                    format!("alter sequence {}.{} set logged;", self.schema, self.name)
                        .with_empty_lines();
            }
        }

        if let Some(start_value) = self.start_value {
            clauses.push(format!("start with {start_value}"));
            // Emit RESTART WITH only when the effective current position (last_value if
            // available, otherwise old start_value) lies below the new MINVALUE.  Any other
            // restart would risk rewinding a live sequence.
            if let Some(new_minvalue) = self.min_value {
                let effective_current = from.last_value.or(from.start_value).unwrap_or(start_value);
                if effective_current < new_minvalue {
                    clauses.push(format!("restart with {start_value}"));
                }
            }
        }
        if let Some(increment_by) = self.increment_by {
            clauses.push(format!("increment by {increment_by}"));
        }
        if let Some(min_value) = self.min_value {
            clauses.push(format!("minvalue {min_value}"));
        } else {
            clauses.push("no minvalue".to_string());
        }
        if let Some(max_value) = self.max_value {
            clauses.push(format!("maxvalue {max_value}"));
        } else {
            clauses.push("no maxvalue".to_string());
        }
        if let Some(cache_size) = self.cache_size {
            clauses.push(format!("cache {cache_size}"));
        }
        clauses.push(if self.cycle {
            "cycle".to_string()
        } else {
            "no cycle".to_string()
        });

        if let Some(owned_by) = self.render_owned_by_clause() {
            clauses.push(owned_by);
        }

        let mut script = logging_script;
        script.push_str(&format!("alter sequence {}.{}", self.schema, self.name));

        if !clauses.is_empty() {
            script.push(' ');
            script.push_str(&clauses.join(" "));
        }

        script.append_block(";");

        script.push_str(&self.get_owner_script());

        if let Some(comment) = &self.comment {
            script.append_block(&format!(
                "comment on sequence {}.{} is '{}';",
                self.schema,
                self.name,
                comment.replace('\'', "''")
            ));
        }

        script
    }

    pub fn get_owner_script(&self) -> String {
        if self.owner.is_empty() {
            return String::new();
        }

        format!(
            "alter sequence {}.{} owner to {};",
            self.schema, self.name, self.owner
        )
        .with_empty_lines()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn build_sequence() -> Sequence {
        Sequence::new(
            "public".to_string(),
            "order_id_seq".to_string(),
            "postgres".to_string(),
            "bigint".to_string(),
            Some(1),
            Some(1),
            Some(1000),
            Some(5),
            true,
            Some(20),
            Some(42),
            Some("public".to_string()),
            Some("orders".to_string()),
            Some("id".to_string()),
        )
    }

    #[test]
    fn test_sequence_new_initializes_hash() {
        let sequence = build_sequence();

        let mut hasher = Sha256::new();
        hasher.update("public".as_bytes());
        hasher.update("order_id_seq".as_bytes());
        hasher.update("postgres".as_bytes());
        hasher.update("bigint".as_bytes());
        hasher.update("1".as_bytes());
        hasher.update("1".as_bytes());
        hasher.update("1000".as_bytes());
        hasher.update("5".as_bytes());
        hasher.update("true".as_bytes());
        hasher.update("20".as_bytes());
        hasher.update("false".as_bytes()); // is_identity
        hasher.update("false".as_bytes()); // is_unlogged

        let expected_hash = format!("{:x}", hasher.finalize());

        assert_eq!(sequence.hash.as_deref(), Some(expected_hash.as_str()));
    }

    #[test]
    fn test_get_script_with_all_options() {
        let sequence = build_sequence();

        let script = sequence.get_script();

        assert_eq!(
            script,
            "create sequence public.order_id_seq start with 1 increment by 5 minvalue 1 maxvalue 1000 cache 20 cycle;\n\nalter sequence public.order_id_seq owner to postgres;\n\n",
        );
    }

    #[test]
    fn test_get_script_uses_defaults() {
        let sequence = Sequence::new(
            "public".to_string(),
            "minimal_seq".to_string(),
            "postgres".to_string(),
            "bigint".to_string(),
            None,
            None,
            None,
            None,
            false,
            None,
            None,
            None,
            None,
            None,
        );

        assert_eq!(
            sequence.get_script(),
            "create sequence public.minimal_seq no minvalue no maxvalue no cycle;\n\nalter sequence public.minimal_seq owner to postgres;\n\n",
        );
    }

    #[test]
    fn test_get_drop_script() {
        let sequence = build_sequence();
        assert_eq!(
            sequence.get_drop_script(),
            "drop sequence if exists public.order_id_seq;\n\n"
        );
    }

    #[test]
    fn test_get_alter_script_includes_owned_by() {
        let sequence = build_sequence();

        // start_value unchanged (from == to == 1): no RESTART WITH expected.
        assert_eq!(
            sequence.get_alter_script(&sequence.clone()),
            "alter sequence public.order_id_seq start with 1 increment by 5 minvalue 1 maxvalue 1000 cache 20 cycle owned by public.orders.id;\n\nalter sequence public.order_id_seq owner to postgres;\n\n",
        );
    }

    #[test]
    fn test_get_alter_script_escapes_owned_by_identifiers() {
        let sequence = Sequence::new(
            "audit".to_string(),
            "event_seq".to_string(),
            "postgres".to_string(),
            "bigint".to_string(),
            Some(10),
            None,
            None,
            Some(2),
            false,
            None,
            None,
            Some("\"my\"\"schema\"".to_string()),
            Some("\"my.table\"".to_string()),
            Some("column".to_string()),
        );

        // start_value unchanged (from == to == 10): no RESTART WITH expected.
        assert_eq!(
            sequence.get_alter_script(&sequence.clone()),
            "alter sequence audit.event_seq start with 10 increment by 2 no minvalue no maxvalue no cycle owned by \"my\"\"schema\".\"my.table\".column;\n\nalter sequence audit.event_seq owner to postgres;\n\n",
        );
    }

    /// Regression test: when MINVALUE is raised above the sequence's previously recorded start
    /// value (e.g. 1), an ALTER SEQUENCE without RESTART WITH causes PostgreSQL to implicitly
    /// restart from the old start value, which violates the new MINVALUE constraint:
    ///
    ///   ERROR: RESTART value (1) cannot be less than MINVALUE (10000000)
    ///
    /// The generated script must include an explicit RESTART WITH equal to START WITH so that
    /// the current sequence position is repositioned to the new value before the constraint
    /// check is applied.
    #[test]
    fn test_get_alter_script_restart_with_matches_start_with_when_minvalue_raised() {
        let from_sequence = Sequence::new(
            "my_schema".to_string(),
            "my_sequence_id_seq".to_string(),
            "postgres".to_string(),
            "bigint".to_string(),
            Some(1), // old start_value
            Some(1),
            Some(999_999_999),
            Some(1),
            false,
            Some(1),
            None,
            None,
            None,
            None,
        );
        let to_sequence = Sequence::new(
            "my_schema".to_string(),
            "my_sequence_id_seq".to_string(),
            "postgres".to_string(),
            "bigint".to_string(),
            Some(10_000_000), // new start_value — also serves as the new MINVALUE
            Some(10_000_000), // MINVALUE raised well above the old start value of 1
            Some(999_999_999),
            Some(1),
            true,
            Some(1),
            None,
            None,
            None,
            None,
        );

        let script = to_sequence.get_alter_script(&from_sequence);

        // Both clauses must appear so that PostgreSQL does not fall back to the old start value.
        assert!(
            script.contains("start with 10000000"),
            "script must contain START WITH: {script}"
        );
        assert!(
            script.contains("restart with 10000000"),
            "script must contain RESTART WITH to avoid RESTART value < MINVALUE error: {script}"
        );
        assert_eq!(
            script,
            "alter sequence my_schema.my_sequence_id_seq start with 10000000 restart with 10000000 increment by 1 minvalue 10000000 maxvalue 999999999 cache 1 cycle;\n\nalter sequence my_schema.my_sequence_id_seq owner to postgres;\n\n",
        );
    }

    /// RESTART WITH must NOT be emitted when the sequence's effective current position
    /// (last_value) is already above the new MINVALUE — even when start_value and MINVALUE are
    /// both raised.  Emitting it would rewind the live sequence from its current position back
    /// to the new start_value, risking duplicate-key violations.
    #[test]
    fn test_get_alter_script_no_restart_when_last_value_above_new_minvalue() {
        let from_sequence = Sequence::new(
            "public".to_string(),
            "busy_seq".to_string(),
            "postgres".to_string(),
            "bigint".to_string(),
            Some(1),
            Some(1),
            Some(999_999_999),
            Some(1),
            false,
            Some(1),
            Some(15_000_000), // sequence is already well above the new MINVALUE
            None,
            None,
            None,
        );
        let to_sequence = Sequence::new(
            "public".to_string(),
            "busy_seq".to_string(),
            "postgres".to_string(),
            "bigint".to_string(),
            Some(10_000_000), // start_value raised
            Some(10_000_000), // MINVALUE raised — but last_value (15M) is already above it
            Some(999_999_999),
            Some(1),
            false,
            Some(1),
            None,
            None,
            None,
            None,
        );

        let script = to_sequence.get_alter_script(&from_sequence);

        assert!(
            !script.contains("restart with"),
            "script must NOT contain RESTART WITH when last_value ({}) is already above new MINVALUE (10000000): {script}",
            15_000_000
        );
        assert!(
            script.contains("start with 10000000"),
            "script must still update START WITH: {script}"
        );
    }

    /// When only non-start/minvalue parameters change (e.g. cycle) and the effective current
    /// position is already within the new bounds, RESTART WITH must NOT be emitted.
    #[test]
    fn test_get_alter_script_no_restart_when_only_other_params_change() {
        let from_sequence = Sequence::new(
            "public".to_string(),
            "live_seq".to_string(),
            "postgres".to_string(),
            "bigint".to_string(),
            Some(1),
            Some(1),
            Some(9999),
            Some(1),
            false, // cycle was false
            Some(1),
            Some(500_000), // current live position
            None,
            None,
            None,
        );
        let to_sequence = Sequence::new(
            "public".to_string(),
            "live_seq".to_string(),
            "postgres".to_string(),
            "bigint".to_string(),
            Some(1), // start_value unchanged
            Some(1),
            Some(9999),
            Some(1),
            true, // only cycle changed
            Some(1),
            None,
            None,
            None,
            None,
        );

        let script = to_sequence.get_alter_script(&from_sequence);

        assert!(
            !script.contains("restart with"),
            "script must NOT contain RESTART WITH when start_value is unchanged: {script}"
        );
    }
}
