use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::utils::string_extensions::StringExt;

// This is an information about a PostgreSQL sequence.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Sequence {
    pub schema: String,                  // Schema where the sequence is defined
    pub name: String,                    // Name of the sequence
    pub owner: String,                   // Owner of the sequence
    pub data_type: String,               // Data type of the sequence
    pub start_value: Option<i64>,        // Start value of the sequence
    pub min_value: Option<i64>,          // Minimum value of the sequence
    pub max_value: Option<i64>,          // Maximum value of the sequence
    pub increment_by: Option<i64>,       // Increment value of the sequence
    pub cycle: bool,                     // Whether the sequence cycles
    pub cache_size: Option<i64>,         // Cache size of the sequence
    pub last_value: Option<i64>,         // Last value generated by the sequence
    pub owned_by_schema: Option<String>, // Schema of the owning table/column
    pub owned_by_table: Option<String>,  // Owning table name
    pub owned_by_column: Option<String>, // Owning column name
    pub is_identity: bool,               // Whether the sequence is an identity sequence
    #[serde(default)]
    pub is_unlogged: bool, // Whether the sequence is unlogged (relpersistence = 'u')
    #[serde(default)]
    pub comment: Option<String>, // Optional sequence comment
    pub hash: Option<String>,            // Hash of the sequence
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub acl: Vec<String>, // ACL (grant) entries for this sequence
}

impl Sequence {
    /// Creates a new Sequence with the given parameters
    #[allow(clippy::too_many_arguments)] // Sequence metadata naturally includes these fields from pg_sequence and pg_class.
    pub fn new(
        schema: String,
        name: String,
        owner: String,
        data_type: String,
        start_value: Option<i64>,
        min_value: Option<i64>,
        max_value: Option<i64>,
        increment_by: Option<i64>,
        cycle: bool,
        cache_size: Option<i64>,
        last_value: Option<i64>,
        owned_by_schema: Option<String>,
        owned_by_table: Option<String>,
        owned_by_column: Option<String>,
    ) -> Self {
        let mut sequence = Self {
            schema,
            name,
            owner,
            data_type,
            start_value,
            min_value,
            max_value,
            increment_by,
            cycle,
            cache_size,
            last_value,
            owned_by_schema,
            owned_by_table,
            owned_by_column,
            is_identity: false,
            is_unlogged: false,
            comment: None,
            hash: None,
            acl: Vec::new(),
        };
        sequence.hash();
        sequence
    }

    pub fn set_is_identity(&mut self, is_identity: bool) {
        self.is_identity = is_identity;
        self.hash();
    }

    /// Hash
    pub fn hash(&mut self) {
        let mut hasher = Sha256::new();

        hasher.update(self.schema.as_bytes());
        hasher.update(self.name.as_bytes());
        hasher.update(self.owner.as_bytes());
        hasher.update(self.data_type.as_bytes());
        if let Some(start_value) = self.start_value {
            hasher.update(start_value.to_string().as_bytes());
        }
        if let Some(min_value) = self.min_value {
            hasher.update(min_value.to_string().as_bytes());
        }
        if let Some(max_value) = self.max_value {
            hasher.update(max_value.to_string().as_bytes());
        }
        if let Some(increment_by) = self.increment_by {
            hasher.update(increment_by.to_string().as_bytes());
        }
        hasher.update(self.cycle.to_string().as_bytes());
        if let Some(cache_size) = self.cache_size {
            hasher.update(cache_size.to_string().as_bytes());
        }
        hasher.update(self.is_identity.to_string().as_bytes());
        hasher.update(self.is_unlogged.to_string().as_bytes());
        if let Some(comment) = &self.comment {
            hasher.update(comment.as_bytes());
        }

        self.hash = Some(format!("{:x}", hasher.finalize()));
    }

    fn render_owned_by_clause(&self) -> Option<String> {
        if self.is_identity {
            return None;
        }
        match (
            self.owned_by_schema.as_deref(),
            self.owned_by_table.as_deref(),
            self.owned_by_column.as_deref(),
        ) {
            (Some(schema), Some(table), Some(column)) => {
                Some(format!("owned by {}.{}.{}", schema, table, column))
            }
            _ => None,
        }
    }

    /// Returns a string representation of the sequence
    pub fn get_script(&self) -> String {
        let mut script = String::new();

        // CREATE SEQUENCE statement
        if self.is_unlogged {
            script.push_str(&format!(
                "create unlogged sequence {}.{}",
                self.schema, self.name
            ));
        } else {
            script.push_str(&format!("create sequence {}.{}", self.schema, self.name));
        }

        // Add AS clause for data type if not default
        if !self.data_type.is_empty() && self.data_type != "bigint" {
            script.push_str(&format!(" as {}", self.data_type));
        }

        // Add START WITH clause
        if let Some(start_value) = self.start_value {
            script.push_str(&format!(" start with {start_value}"));
        }

        // Add INCREMENT BY clause
        if let Some(increment_by) = self.increment_by
            && increment_by != 1
        {
            script.push_str(&format!(" increment by {increment_by}"));
        }

        // Add MINVALUE clause
        if let Some(min_value) = self.min_value {
            script.push_str(&format!(" minvalue {min_value}"));
        } else {
            script.push_str(" no minvalue");
        }

        // Add MAXVALUE clause
        if let Some(max_value) = self.max_value {
            script.push_str(&format!(" maxvalue {max_value}"));
        } else {
            script.push_str(" no maxvalue");
        }

        // Add CACHE clause
        if let Some(cache_size) = self.cache_size
            && cache_size != 1
        {
            script.push_str(&format!(" cache {cache_size}"));
        }

        // Add CYCLE clause
        if self.cycle {
            script.push_str(" cycle");
        } else {
            script.push_str(" no cycle");
        }

        script.append_block(";");

        script.push_str(&self.get_owner_script());

        if let Some(comment) = &self.comment {
            script.append_block(&format!(
                "comment on sequence {}.{} is '{}';",
                self.schema,
                self.name,
                comment.replace('\'', "''")
            ));
        }

        script
    }

    pub fn get_drop_script(&self) -> String {
        format!("drop sequence if exists {}.{};", self.schema, self.name).with_empty_lines()
    }

    /// Generates an ALTER SEQUENCE script targeting `self` (the desired state).
    ///
    /// `from` is the prior sequence state (always required — callers that own the comparer
    /// always have it).  `RESTART WITH` is emitted only when the sequence's effective current
    /// position would fall below the new `MINVALUE`, i.e. when
    /// `effective_current < new_minvalue` where
    /// `effective_current = from.last_value ?? from.start_value`.
    ///
    /// This is the minimal condition required to prevent PostgreSQL from rejecting the
    /// statement with:
    ///
    ///   ERROR: RESTART value (1) cannot be less than MINVALUE (10000000)
    ///
    /// Emitting `RESTART WITH` unconditionally (e.g. whenever `start_value` differs)
    /// would rewind a live sequence whose current position is already above the new
    /// `start_value`, risking duplicate-key violations.
    pub fn get_alter_script(&self, from: &Sequence) -> String {
        self.build_alter_script(from, true)
    }

    /// Same as [`Self::get_alter_script`] but never emits the
    /// `ALTER SEQUENCE ... SET LOGGED|UNLOGGED` line. The comparer
    /// uses this when the owning table is itself flipping persistence
    /// in the same migration: PostgreSQL automatically propagates the
    /// table's `ALTER TABLE SET LOGGED|UNLOGGED` to every owned
    /// sequence, so re-emitting the SET on the sequence is redundant
    /// (issue #180).
    pub fn get_alter_script_excluding_persistence(&self, from: &Sequence) -> String {
        self.build_alter_script(from, false)
    }

    /// True when the only field that differs between `self` (TO) and
    /// `from` is `is_unlogged`. Used by the comparer to suppress an
    /// otherwise no-op `ALTER SEQUENCE …` for owned sequences whose
    /// owning table is flipping persistence (the table's `ALTER TABLE
    /// SET LOGGED|UNLOGGED` propagates to the sequence on its own —
    /// re-emitting the full clause list would be cosmetic noise).
    ///
    /// Implementation strategy: clone `self`, force its `is_unlogged`
    /// back to `from`'s value, recompute the hash, and compare. This
    /// piggy-backs on [`Self::hash`] so any new field added to the
    /// hash is automatically considered here — there's no field list
    /// to forget to update. We also explicitly compare the few fields
    /// that `hash()` deliberately leaves out but `get_alter_script`
    /// renders (`owned_by_*`); a change there must still block the
    /// suppression because the table-cascade does NOT propagate
    /// ownership changes.
    pub fn is_only_persistence_change(&self, from: &Sequence) -> bool {
        if self.is_unlogged == from.is_unlogged {
            return false;
        }
        // Hash mismatch on the persistence-equalised clone means SOME
        // hashed field other than `is_unlogged` differs.
        let mut probe = self.clone();
        probe.is_unlogged = from.is_unlogged;
        probe.hash();
        if probe.hash != from.hash {
            return false;
        }
        // Ownership info is rendered in `get_alter_script` but not
        // hashed — keep the explicit checks as a belt-and-braces guard
        // against a behaviour-affecting change being silently dropped.
        self.owned_by_schema == from.owned_by_schema
            && self.owned_by_table == from.owned_by_table
            && self.owned_by_column == from.owned_by_column
    }

    fn build_alter_script(&self, from: &Sequence, include_persistence: bool) -> String {
        let mut clauses = Vec::new();

        // Handle logged/unlogged change
        let mut logging_script = String::new();
        if include_persistence && self.is_unlogged != from.is_unlogged {
            if self.is_unlogged {
                logging_script =
                    format!("alter sequence {}.{} set unlogged;", self.schema, self.name)
                        .with_empty_lines();
            } else {
                logging_script =
                    format!("alter sequence {}.{} set logged;", self.schema, self.name)
                        .with_empty_lines();
            }
        }

        if let Some(start_value) = self.start_value {
            clauses.push(format!("start with {start_value}"));
            // Emit RESTART WITH only when the effective current position (last_value if
            // available, otherwise old start_value) lies below the new MINVALUE.  Any other
            // restart would risk rewinding a live sequence.
            if let Some(new_minvalue) = self.min_value {
                let effective_current = from.last_value.or(from.start_value).unwrap_or(start_value);
                if effective_current < new_minvalue {
                    clauses.push(format!("restart with {start_value}"));
                }
            }
        }
        if let Some(increment_by) = self.increment_by {
            clauses.push(format!("increment by {increment_by}"));
        }
        if let Some(min_value) = self.min_value {
            clauses.push(format!("minvalue {min_value}"));
        } else {
            clauses.push("no minvalue".to_string());
        }
        if let Some(max_value) = self.max_value {
            clauses.push(format!("maxvalue {max_value}"));
        } else {
            clauses.push("no maxvalue".to_string());
        }
        if let Some(cache_size) = self.cache_size {
            clauses.push(format!("cache {cache_size}"));
        }
        clauses.push(if self.cycle {
            "cycle".to_string()
        } else {
            "no cycle".to_string()
        });

        if let Some(owned_by) = self.render_owned_by_clause() {
            clauses.push(owned_by);
        }

        let mut script = logging_script;
        script.push_str(&format!("alter sequence {}.{}", self.schema, self.name));

        if !clauses.is_empty() {
            script.push(' ');
            script.push_str(&clauses.join(" "));
        }

        script.append_block(";");

        script.push_str(&self.get_owner_script());

        if let Some(comment) = &self.comment {
            script.append_block(&format!(
                "comment on sequence {}.{} is '{}';",
                self.schema,
                self.name,
                comment.replace('\'', "''")
            ));
        }

        script
    }

    pub fn get_owner_script(&self) -> String {
        if self.owner.is_empty() {
            return String::new();
        }

        format!(
            "alter sequence {}.{} owner to {};",
            self.schema, self.name, self.owner
        )
        .with_empty_lines()
    }
}

#[cfg(test)]
#[path = "sequence_tests.rs"]
mod tests;
