use crate::dump::dump::Dump;
use std::{
    fs::File,
    io::{Error, Write},
};

// 
pub struct Comparer {
    from: Dump,
    to: Dump,

    script: String,
}

impl Comparer {
    pub fn new(from: Dump, to: Dump) -> Self {
        let mut comparer = Self {
            from,
            to,
            script: String::new(),
        };

        comparer.script.push_str("/*\n");
        comparer
            .script
            .push_str("Script generated by PostgreSQL Comparer\n\n");
        comparer.script.push_str(" From dump:\n");
        comparer.script.push_str(&comparer.from.get_info());
        comparer.script.push_str("\n\n To dump:\n");
        comparer.script.push_str(&comparer.to.get_info());
        comparer.script.push_str("\n\n Comparison results:\n");
        comparer.script.push_str("*/\n\n");

        comparer
    }

    pub async fn compare(&self) -> Result<(), Error> {
        self.compare_extensions().await?;
        self.compare_types().await?;
        self.compare_enums().await?;
        self.compare_routines().await?;
        self.compare_tables().await?;

        Ok(())
    }

    fn get_script(&self) -> String {
        self.script.clone()
    }

    pub async fn save_script(&self, output: &str) -> Result<(), Error> {
        let mut file = File::create_new(output)?;
        file.write_all(self.get_script().as_bytes())?;
        Ok(())
    }
}
