use std::{fs::File, io::{Error, Write}};

use crate::dump::dump::Dump;

pub struct Comparer {
    from: Dump,
    to: Dump,
}

impl Comparer {
    pub fn new(from: Dump, to: Dump) -> Self {
        Self { from, to }
    }

    pub async fn compare(&self) -> Result<(), Error> {
        Ok(())
    }

    fn get_script(&self) -> String {
        let mut script = String::new();
        script.push_str("/*\n");
        script.push_str("Script generated by pgc\n\n");
        script.push_str(" From dump:\n");
        script.push_str(&self.from.get_info());
        script.push_str("\n\n To dump:\n");
        script.push_str(&self.to.get_info());
        script.push_str("\n\n Comparison results:\n");
        script.push_str("*/\n\n");
        script.push_str("/* Comparison logic not implemented yet */\n");
        script
    }

    pub async fn save_script(&self, output: &str) -> Result<(), Error> {
        let mut file = File::create_new(output)?;
        file.write_all(self.get_script().as_bytes())?;
        Ok(())
    }
}