-- Script generated by pgc

-- From dump:
	Connection Info:
		- Host: localhost
		- Port: 5432
		- User: postgres
		- Database: postgres
		- Scheme: public
		- SSL: false
	Dump Info:
		- File: dump.io
		- Extensions: 0
		- Types: 0
		- Enums: 0
		- Routines: 0
		- Tables: 0

-- To dump:
	Connection Info:
		- Host: localhost
		- Port: 5432
		- User: postgres
		- Database: postgres
		- Scheme: public
		- SSL: false
	Dump Info:
		- File: dump.io
		- Extensions: 0
		- Types: 0
		- Enums: 0
		- Routines: 0
		- Tables: 1

-- Comparison results:
/* Comparison logic not implemented yet */
